Exception exception = new Exception("Error de prueba");

throw exception; // Lanza la excepción
// El programa se detiene aquí y no se ejecuta el siguiente código


